image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:14.04

variables:
  PATCH: $CI_BUILD_ID

stages:
  - pack

pack:
  stage: pack
  script:
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install -y --force-yes curl jq
    - curl -sL https://deb.nodesource.com/setup_6.x > nodejs-repo
    - chmod +x nodejs-repo
    - ./nodejs-repo
    - apt-get install -y --force-yes nodejs node-gyp libzmq-dev build-essential git python-pip libpython-dev pkg-config libhdf5-dev libatlas-dev python-h5py python-numpy
    - make pack
    - tar -czvf `ls -d baserunner-*`.tar.gz baserunner-*
  artifacts:
    paths:
      - ./*.tar.gz
