image: docker-registry.oxfordnanolabs.local:5000/ont-base-ubuntu:14.04

variables:
  REPO_DEVELOPMENT: "trusty-unstable"
  REPO_STAGING:     "trusty-testing"
  REPO_PRODUCTION:  "trusty-stable"
  LC_BASENAME:      "gitlab-portal-lc"
  PATCH:            $CI_BUILD_ID
  TAG_NAME:         "portal-web"
  TAG_PROJECT:      "portal"
  TAG_TEAM:         "metrichor"
  TAG_OWNER:        "gitlab-ci"

stages:
  - pack

pack:
  stage: pack
  script:
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install curl -y --force-yes
    - curl -sL https://deb.nodesource.com/setup_6.x > nodejs-repo
    - chmod +x nodejs-repo
    - ./nodejs-repo
    - apt-get install nodejs libzmq-dev virtualenv build-essential git
    - make pack
    - tar -czvf `ls -d baserunner-*`.tar.gz baserunner-*
  artifacts:
    paths:
      - ./*.tar.gz
